### ISSUE TITLE
sdk-go: provide underlying error when logging

### ISSUE THREAD

**Issue by wasaga** [pomerium/sdk-go#110]
https://github.com/pomerium/sdk-go/blob/ee196f830fc7f8c1f03dd1164ed8cdf447128558/sdk.go#L169

will log something like 

```
{"level":"info","time":"2023-11-10T03:32:33Z","message":"KeyID: 99b7e7cd59127f18c6a17f3ef7f8a5403ee99139a5b140ec86c6e0fad75c3622 not found, fetching jwks endpoint: https://(redacted)/.well-known/pomerium/jwks.json"}
```

which is misleading as the key is there (validated with curl -k) - the root cause is TLS error, which is not provided in the log message.

**Comment by calebdoxsey** [comment]
I don't know the context of this issue, but this log message:

```json
{
  "level":"info",
  "time":"2023-11-10T03:32:33Z",
  "message":"KeyID: 99b7e7cd59127f18c6a17f3ef7f8a5403ee99139a5b140ec86c6e0fad75c3622 not found, fetching jwks endpoint: https://(redacted)/.well-known/pomerium/jwks.json"
}
```

Occurs before the error, so it should not include the TLS error. It's not misleading. The key is in fact not there and has to be retrieved. When it's retrieved an error occurs and is returned from the `GetIdentity` function, which is then added to the context and retrieved via `sdk.FromContext`. 

In the verify application that error is set to the response and will appear on the page:

```
identity, err := sdk.FromContext(r.Context())
res["error"] = err.Error()
```

Without more details about the desired changes I don't know how to proceed.
